name: Go-Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: .
        run: go get -v -t -d ./...

      - name: Set version as variable
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Build
        working-directory: .
        run: mkdir http-to-kafka-linux-amd64-${{ env.VERSION }} && go build -v -o http-to-kafka-linux-amd64-${{ env.VERSION }} ./...

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: http-to-kafka-linux-amd64-${{ env.VERSION }}
          path: ./http-to-kafka-*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            aerisconsulting/http-to-kafka:latest
            aerisconsulting/http-to-kafka:${{ env.VERSION }}
