name: Go-Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-latest' ]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        working-directory: .
        run: go get -v -t -d ./...

      - name: Build
        working-directory: .
        run: mkdir http-to-kafka-macos-amd64 && go build -v -o http-to-kafka-macos-amd64 ./...

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: http-to-kafka-macos-amd64
          path: ./http-to-kafka-*